name: Build

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: ./gradlew assembleRelease

      - name: Run unit tests
        run: ./gradlew testReleaseUnitTest

      - uses: actions/upload-artifact@v7
        name: Upload APK artifact
        with:
          name: app-release-unsigned.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk

      - uses: actions/upload-artifact@v7
        name: Upload unit test report
        if: always()
        with:
          name: Unit test report
          path: app/build/reports/tests/testReleaseUnitTest/
